### PR TITLE
fix: update console dispatch_release and dispatch_daily_build workflow

### PR DESCRIPTION
**Pull request by WANZARGEN**
# Description

- Added a turbo_cache service to the docker job.

### CODE REVIEW

**Comment by GeunjeLEE** [comment]
@WANZARGEN 
`service` keyword seems to be a container that provides turbo cache.
Is it instead of EC2? You've finally found the most efficient way to serve Turbo Cache!
That's cool!

But, just one thing.
i'm don't recommend using `latest` tag, because It can break immutability and make debugging difficult.
How about using semantic versioning?

Also,  i think, `image` of turbo_cache in `service` should be replaced with github secrets,
because Your Dockerhub organizations can be targets of security attacks.

---

See [here](https://github.com/cloudforet-io/actions/pull/29/files#diff-d6352b4ee68ab7ecb1f9612748fdba345dd6da508d439e9688eab50e6d8cdbdfR17)

```diff
- image: wanzargen/turbo-cache-server:latest
+ image: ${{ github.secrets.tubo_cache_image }}:0.0.1
```

**Review by GeunjeLEE — APPROVED** [review]
Thank you for accepting my feedback 👍 
I will merge this PR.

**Comment by WANZARGEN** [comment]
> Also, i think, image of turbo_cache in service should be replaced with github secrets,
because Your Dockerhub organizations can be targets of security attacks.

I applied your advice and tested it in my repo, but there is an error as below. 
image

I think github action can not access to the secrets in running service step. 🥲
So I rollbacked this commit.
But I applied versioning you mentioned! 🙂

Additionally, I have a question. 🤔
Public docker images are used in many cases.
I don't know why it is dangerous and it can be targeted of security attacks. 
There is no security information inside the image. 😯

**Comment by GeunjeLEE** [comment]
@WANZARGEN 
> I think github action can not access to the secrets in service running step. 🥲
I applied versioning, but using secrets is not work, so I need to rollback.

~~Oh. Sorry about that...
correct format is `${{ secrets.secret_name }}`, you can get usage in this [document](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)~~
How stupid i said.... I will find out if there is a usage of secret in the service keyword and share it.

>Additionally, public docker images is used in many cases.
I don't know why it is dangerous and it can be targeted of security attacks since that image has no security information inside the image. 😯

Yes i agree with you, But I just don't want to leave clues about security incidents.
If you don't agree my opinion, you can take your way : )

**Comment by WANZARGEN** [comment]
> Yes i agree with you, But I just don't want to leave clues about security incidents.
If you don't agree my opinion, you can take your way : )

Oh, actually I just wanted to know what kind of security attacks can be occurred exactly since I am new to this area 😅

**Comment by WANZARGEN** [comment]
> correct format is ${{ secrets.secret_name }}, you can get usage in this [document](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow)

Oh, Did I use in wrong format?  😱
I cannot find it... Can you give me a suggestion? I can not figure out what's wrong with mine...😭
```
image: ${{ secrets.TURBO_CACHE_SERVER_IMAGE }}
```

**Comment by WANZARGEN** [comment]
> How stupid i said.... I will find out if there is a usage of secret in the service keyword and share it.

Oh, thank you so much @GeunjeLEE  !!! 😍

**Comment by GeunjeLEE** [comment]
@WANZARGEN 
> I applied your advice and tested it in my repo, but there is an error as below.

Your syntax was right. `Secret` expression(?) can't be in `image`, Choose your original way.

> Oh, actually I just wanted to know what kind of security attacks can be occurred exactly since I am new to this area 

If someone gets permission from a docker organization and uploads an infected image, unexpected behavior may occur.
So, I don't want to expose the repository's organization or image version.

In this case, since we are putting the Turbo Key on Container, I think that an accident in which it is exposed may occur.
(If we are unaware that an infected image has been uploaded.)

But, As I said before, It just my opinion (It could be an outdated idea or a bad decision.)

---

Anyway, your commit is cool. 
please merge this PR and Sync workflows on console repository. :)

**Comment by WANZARGEN** [comment]
@GeunjeLEE 
> If someone gets permission from a docker organization and uploads an infected image, unexpected behavior may occur.
In this case, since we are putting the Turbo Key on Container, I think that an accident in which it is exposed may occur.
But, As I said before, It just my opinion (It could be an outdated idea or a bad decision.)

Thank you for giving me an information about potential risks. 🙏
But there aren't any credentials in the image, so I think it's gonna be alright. :)
Turbo token will be passed when the action runs the turbo_cache service container.
That is this part:
```
        env:
          PORT: 3000
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
          STORAGE_PROVIDER: git-repository
          STORAGE_PATH: console-artifacts
          GIT_REPOSITORY: ${{ vars.TURBO_CACHE_SERVER_GIT_REPOSITORY }}
          GIT_BRANCH: ${{ vars.TURBO_CACHE_SERVER_GIT_BRANCH }}
          GIT_USER_NAME: ${{ vars.GIT_USERNAME }}
          GIT_USER_EMAIL: ${{ vars.GIT_EMAIL }}
          GIT_USER_PASSWORD: ${{ secrets.PAT_TOKEN }}
```

Thank you for very detailed information again. 😄

**Comment by WANZARGEN** [comment]
@GeunjeLEE 
Oh, I think I misunderstood. 
You pointed the case that if somebody uploads an infected image. 🤔
I've never thought of that case.
I will take my docker hub credentials more carefully to prevent others from uploading images with security issues to my Docker repository.  
Thank you for your advice again. 🫡

**Pull request merged**
